/**
 * Data.js
 * This file contains string constants used throughout the application for various services and user actions.
 */

const data = {
    // Verification Services
    panverify: "Pan Number Verification Api Service Provided By NTAR PRIVATE LIMITED",
    aadhaarVerify: "Aadhaar Verification Api Service Provided By NTAR PRIVATE LIMITED",
    mobileVerify: "Mobile Number Verification Api Service Provided By NTAR PRIVATE LIMITED",
    cinVerification: "CIN VERIFICATION Api Service Provided By NTAR PRIVATE LIMITED",
    faceMatch: "FACE MATCH VERIFICATION Api Service Provided By NTAR PRIVATE LIMITED",
    gst_in_verification: "GST_IN VERIFICATION Api Service Provided By NTAR PRIVATE LIMITED",
    AccountVerify: "Account Verification Api Service Provided By NTAR PRIVATE LIMITED",
    NameVerify: "Names Verification Api Service Provided By NTAR PRIVATE LIMITED",
    HolderNameVerify: "Account Holder Name Verification Api Service Provided By NTAR PRIVATE LIMITED",
    panNameVerify: "Pan Name Verification Api Service Provided By NTAR PRIVATE LIMITED",
    DobVerify: "Date of Birth Verification using Pan Number Api Service Provided By NTAR PRIVATE LIMITED",
    shopEstablishment: "Shop Establishment Verification Api Service Provided By NTAR PRIVATE LIMITED",
    binVerify: "Bin Number Verification Api Service Provided By NTAR PRIVATE LIMITED",
    ifscVerify: "IFSC Code Verification Api Service Provided By NTAR PRIVATE LIMITED",

    // User Actions
    showPass: "Show Password",
    havingAccount: "Already Have an Account Login Here... →",
    notHavingAccount: "Don't Have an Account Register Here... →",
    register: "Register",
    submit: "Submit",
    cancel: "Cancel",
    login: "LOGIN",
    registerToContinue: "Register To Continue",

    // Documentataion
    clientHeader : {
        client_id: "client_id",
        secret_key: "secret_key",
        content_type: "Application/json",
        },

    // Messages
    res: "Response",
    LiveApiKeys : "Live API Keys",
    verify: "Verify",
    success: "Success",
    go : "Go Back Dashboard",
    Female : "Female",
    oops : "Oops! The page you're looking for doesn't exist.",
    imageValid : "You can upload anytype of image without any restriction",
    pfirst : "Pan Number is unique Identification Number of a Each person in india",
    result: "Result",
    message: "Message",
    source: "Source",
    accountNumber: "Account Number",
    numeric : "It should be in Numeric.",
    alphaN : "It should be alphanumeric",
    ifscCode: "IFSC Code",
    beneficiaryName: "Beneficiary Name",
    panHolderName: "Pan Holder Name",
    userImagePreview: "User Image Preview:",
    imageAndAadhaarSubmission: "Image and Aadhaar Submission",
    verifyOtp: "Verify Otp",
    uploadImage: "Upload Image",
    aadhaarNumber: "Aadhaar Number",
    verifyImageWithAadhar: "Verify Image with Aadhar",
    uploadAadharImage: "Upload Aadhar Image:",
    uploadUserImage: "Upload User Image",
    aadharImagePreview: "Aadhar Image Preview:",
    BankAccountVerification : "Bank Account Verification",
    ComparingTwoNamesVerification : "Comparing Two Names Verification",
    NameVerificationoftheAccountHolder : "Name Verification of the Account Holder",
    GetAccountwithIFSC:"Bank Account Verification with IFSC",
    ifscVerification:"IFSC verification to know to your Bank",
    AadhaarNumber : "Aadhaar Number",
    pan : "Pan Number",
    VerificationName:"VerificationName",
    firstName:"First Name",
    secondName:"Second Name",
    panHolder : "Pan Holder Name Verification",
    dob : "Date of Birth Verification using Pan",
    panNumber : "Pan Number Verification",
    dobVerify : "DATE OF BIRTH",
    bin:"Bin Number",
    name:"Name",
    email:"Email",
    mobile : "Mobile Number",
    edit: "Edit User",
    gender: "Gender",
    companyName : "Company Name",
    join : "Joined Us on",
    TestingApiKeys : "Testing Api Keys",
    NoKeysFound : "No Keys Found",
    add : "Add",
    WelcomeToNtar : "Welcome to Ntar !!",
    WelcomeToFlowpipe : "Welcome to Flowpipe !!",
    ProfileDetails : "Profile Details",
    Male : "Male",
    keys : "You should send the your own keys that was generated in ApiKeys",
    ApiRules : "Api Rules",
    Overview : "Overview",
    mandatory : "It is a Mandatory Field",
    FieldDetails : "Field Details",
    Tstep : "This is two step Process",
    Fstep : "This is only one step Process",
    headers : "Headers should be sent in Correct format",
    valid : "Field Validation",
    client : "You should send the your client_id and secret_key in the Place of Value of client_id and secret_key as shown above",
    liveK : "Generate Live Api Details",
    capital : "It should be provided in Capital only",
    plength : "length should be equal to 10",
    plengthCheck : "length should not be greater than 10 and less or 10",
    pfull : "Permanent Account Number",
    psecond : " Pan Number is with a length of 10 digits containing Alphanumeric characters"
}

export default data